### ISSUE TITLE
Does it still work?

### ISSUE THREAD

**Issue by Heart1010** [fredericseiler/trelabels#10]
I can't see the tag icon here?! Chrome Version 56.0.2924.87 (64-bit)

![image](https://cloud.githubusercontent.com/assets/1481680/23524910/dd2fe55c-ff8c-11e6-879e-a685482e8a67.png)

**Comment by Heart1010** [comment]
Sorry... after a few ctrl+F5 the tag icon is there!

**Comment by fredericseiler** [comment]
Enjoy :smile:
