### ISSUE TITLE
Repeated Menu

### ISSUE THREAD

**Issue by brannonh** [fredericseiler/trelabels#11]
Clicking the tag button multiple times inserts additional menus, resulting in a very long, repeating menu.

![capture](https://cloud.githubusercontent.com/assets/15135353/24412895/59bef1aa-139f-11e7-82ad-39fff85aac96.PNG)
![capture2](https://cloud.githubusercontent.com/assets/15135353/24412894/59bddc3e-139f-11e7-9409-276cfc8953bc.PNG)
![capture3](https://cloud.githubusercontent.com/assets/15135353/24412893/59bd749c-139f-11e7-9ccd-aa14c48f819e.PNG)

**Comment by fredericseiler** [comment]
I can't reproduce this bug. What other extensions for Trello are you using ?

**Comment by brannonh** [comment]
Here is the full list of extensions I have installed:

   - Cisco WebEx Extension (1.0.9)
   - ColorZilla (2.0)
   - Elegantt for Trello (1.0.23)
   - Evernote Web Clipper (6.11)
   - FreeConferenceCall.com Extension (0.0.0.8)
   - GMail to Trello (2.5.1.0)
   - Google Docs (0.9)
   - Google Docs Offline (1.4)
   - Google Sheets (1.1)
   - Google Slides (2.0.56)
   - Salesforce Inbox (13.0)
   - Trelabels for Trello (1.0.11)
   - Trello (0.0.48)
   - Webroot Filtering Extension (1.2.0.73)


Thanks,
Brannon

**Comment by fredericseiler** [comment]
Maybe it's a conflict with another of your installed extensions or a particular setting you enabled in Chrome because nobody else seems to have this issue with Trelabels.

**Comment by brannonh** [comment]
Look at your Chrome extension page. I wasn't the only person experiencing this issue.

**Comment by fredericseiler** [comment]
You're right, I'll do some tests. In the meantime, can you try in an incognito window with only Trelabels enabled ?

**Comment by brannonh** [comment]
Sorry, I forgot to try an incognito window. The environment where I experienced this is at work, so I will do it on Monday.

**Comment by fredericseiler** [comment]
So, what are the results ?

**Comment by fredericseiler** [comment]
I just reproduced the bug with Elegantt for Trello installed.

I will find what's going on between the two.

**Comment by brannonh** [comment]
Wow, I completely forgot about this. I'm so sorry. Glad you were able to reproduce it.

**Comment by fredericseiler** [comment]
Fixed :)
