### ISSUE TITLE
Problem displaying in trello menu

### ISSUE THREAD

**Issue by rodo1991** [fredericseiler/trelabels#15]
![rd_1966](https://user-images.githubusercontent.com/40571228/42940305-43fd4c1c-8b59-11e8-8230-af10d0013734.jpg)
 Past few months this is happening and I didn't find the solution for it. Tried to reinstall the extension and everything and nothing helped... Running the latest Chrome on Mac. Any ideas?

EDIT: Just realised it's happening only after reloading the page.

**Comment by fredericseiler** [comment]
Have you tried without other Trello extensions ?

**Comment by rodo1991** [comment]
Ahhhh I am so sorry I messed up the names of extensions :( Yours is working wonderfully and the problem is with [this one](https://chrome.google.com/webstore/detail/card-colors-for-trello/nodlpencjjlohojddhflnahnfpfanbjm) and even in the reviews people are complaining about it but nobody knows how to contact the author obviously... 

Sorry about the mixup, my fault :)

**Comment by fredericseiler** [comment]
No problem! I'm glad I don't have to investigate on some weird display bug :)
