### ISSUE TITLE
Labels No Longer Show Text

### ISSUE THREAD

**Issue by oleilu** [fredericseiler/trelabels#18]
Just a few moments ago, after I refreshed my Trello page, the trelabels styles with label names have stopped showing text and appear very squished/shortened. Below is a screencapture of the issue.

![Capture_Redacted](https://user-images.githubusercontent.com/51672719/59210098-65aed500-8b72-11e9-9290-934712684b2e.png)

**Comment by kmkiwi** [comment]
I concur...the text has disappeared from the labels. Hopeful for a fix soon as this is such a great feature!

**Comment by oddmorten** [comment]
I have the same issue in my Chrome browser, across all my boards.

**Comment by Deutschi** [comment]
Can confirm, looks like Trello made a little CSS update.

**Comment by fredericseiler** [comment]
I got the 

![image](https://user-images.githubusercontent.com/954168/59254665-ea602880-8c30-11e9-892a-667afa5342dd.png)

**Comment by fredericseiler** [comment]
Fixed, thanks to @Deutschi !
