### ISSUE TITLE
Labels aren't showing text anymore

### ISSUE THREAD

**Issue by CPressley** [fredericseiler/trelabels#20]
Not sure what changed, the extension is still there but my labels are no longer showing text.

**Comment by fredericseiler** [comment]
Do you still have the Trelabels button ?

![image](https://user-images.githubusercontent.com/954168/72284682-e4f11380-3641-11ea-920c-5dc669c8f85e.png)

**Comment by CPressley** [comment]
Wow. I'm an idiot. It worked. So sorry to bug you.

  Camille Pressley
  Recruiting Coordinator
678-521-3419
camille.pressley@gong.io
www.gong.io

**Comment by fredericseiler** [comment]
No problem :smile:
