### ISSUE TITLE
Enhance label design

### ISSUE THREAD

**Issue by julienma** [fredericseiler/trelabels#5]
Hey, I've been using https://chrome.google.com/webstore/detail/card-color-titles-for-tre/hpmobkglehhleflhaefmfajhbdnjmgim for a while, and I'm now using your extension because I like the on/off toggle.

However, I find their labels are a lot more readable (they have no black outline and use bolder font, and have a margin which I find a lot cleaner) than yours, see:

![label-comparison](https://cloud.githubusercontent.com/assets/201897/8209541/b9c096fe-150d-11e5-9451-909a237e3378.png)
(yours' right)

And when I chose to toggle on the labels, I need them to be bold!
Any chance to enhance that design?

Cheers

**Comment by julienma** [comment]
:+1:

**Comment by fredericseiler** [comment]
De rien :)
