### ISSUE TITLE
Prevent labels from shrinking

### ISSUE THREAD

**Issue by ronwarner** [fredericseiler/trelabels#6]
When labels are toggled on, everything is great.  When labels are toggled off, the color marks shrink to a size far smaller than normal Trello label markers.  These are unusable to me.  I would think toggling Trelabels off should put the view back into standard Trello form.  I have to disable the extension but I'll check back occasionally to see if this has been resolved in hopes of turning it back on.

**Comment by fredericseiler** [comment]
Default style added in 297713d.

**Comment by ronwarner** [comment]
You went above and beyond on this.  The new options are spectacular.  Thanks!
