### ISSUE TITLE
Add Safari Extension

### ISSUE THREAD

**Issue by dcalhoun** [fredericseiler/trelabels#9]
The extension is awesome! It'd great to see it available as a [Safari Extension](https://safari-extensions.apple.com) as well. For reference, [here is an example of a project](https://github.com/jxnblk/Twipster) with support for both Chrome and Safari.

Are you open to including a Safari extension?

**Comment by fredericseiler** [comment]
Well, I'll have to install Safari, but yeah, I can give it a try.

**Comment by fredericseiler** [comment]
In fact, I don't really have time or money ($99 to access the Apple Developer Program ? I don't even own any Apple product !) for a Safari extension, but you're free to do it if you want.
